---
- name: Stáhne soubor a nainstaluje ho
  hosts: "{{ seznam_stanic }}"
  
  tasks:
   - name: Vytvoří složku Ansible
     win_file: 
       path: 'C:\Ansible'
       
   - name: Server stáhne soubor z netu
     win_get_url:
       url: "{{ url_adresa }}"
       dest: "{{ cesta_instalacniho_souboru }}"

   - name: Nainstaluje stažený soubor
     win_package:
       product_id: "{{ id_produktu }}"
       path: "{{ cesta_instalacniho_souboru }}"
       state: present

